GET https://misty-tree-6657.fly.dev/api/persons

###

GET https://misty-tree-6657.fly.dev/api/persons/1

###

GET https://misty-tree-6657.fly.dev/api/persons/1234

###

DELETE https://misty-tree-6657.fly.dev/api/persons/1

###

POST https://misty-tree-6657.fly.dev/api/persons
content-type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}
